### ISSUE TITLE
Get to Python 3

### ISSUE THREAD

**Issue by Cromefire** [rtfd/sphinx-autoapi#101]
By assigning a milestone and creating new issues, that show, what need to be changed. I think this will help people to contribute. Or simply update README, if it is already working

**Comment by peterjc** [comment]
See also #120

**Comment by AWhetter** [comment]
Since this issue was opened, Python 3.4, 3.5 and 3.6 have been added to the list of Python versions to test against. I've opened #139 to check how type annotations are being output. astroid 2.0.0 will have support for type comments as well so we should get those for free.
The README still mentions Python 2 but #120 covers fixing that so I'm going to close this issue in favour of the other issues.
